### ISSUE TITLE
Fix CI Release

### ISSUE THREAD

**Issue by Andrapyre** [SquirclesIO/pg-event-store#1]
CI Release is not working. Pulled out from a comment in https://github.com/sbt/sbt-ci-release/issues/294

**Comment by Andrapyre** [comment]
@mbaechler , this should be a quick fix. Just change the final command in your github action to `sbt sonatypeCentralRelease` instead of `sbt ci-release`. Probably `sbt-ci-release` should be refactored to do this automatically with the standard command, but this, at any rate, a quick fix.

**Comment by mbaechler** [comment]
Thanks you very much for your help, this is much appreciated.

I tried your suggestion and it failed for another reason  :

```
[info] set current project to pg-event-store-root (in build file:/home/runner/work/pg-event-store/pg-event-store/)
2024-09-13 16:06:51.025Z error [Sonatype] [BUNDLE_ZIP_ERROR] Error creating bundle zip directory. /home/runner/work/pg-event-store/pg-event-store/target/sonatype-staging/0.0.1-bundle  - (Sonatype.scala:494)
```

See https://github.com/PerformanceIMMO/pg-event-store/actions/runs/10852378766/job/30118397948

**Comment by Andrapyre** [comment]
@mbaechler , ah that's because you need to run +publishSigned first. That's standard if you're working with `sbt-sonatype` directly, but I guess `sbt-ci-release` takes care of this behind the scenes? I will try to commit a PR to `sbt-ci-release` in the coming days so that you can just use the `ci-release` command.

**Comment by mbaechler** [comment]
If I understand correctly, using `sbt-sonatype` directly make me loose PGP_SECRET variable handling.
If you have an idea how to fix `sbt-ci-release`, I'd rather wait for it (or propose the PR myself with little guidance from you).

**Comment by mbaechler** [comment]
Thanks a lot @Andrapyre , it now works with sbt-ci-release
